env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:import/recommended
  - plugin:import/warnings
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - import
  - unused-imports
rules:
  {
    import/named: off,
    import/order:
      [
        error,
        {
          groups: [builtin, external, internal, [parent, sibling], object, type, index],
          'newlines-between': 'always',
          pathGroupsExcludedImportTypes: [builtin],
          alphabetize: { order: asc, caseInsensitive: true },
          pathGroups:
            [
              { pattern: '@/components/common', group: internal, position: before },
              { pattern: '@/components/hooks', group: internal, position: before },
            ],
        },
      ],
    no-use-before-define: off,
    '@typescript-eslint/no-use-before-define': [error],
    no-void: [error, { allowAsStatement: true }],
    react/function-component-definition:
      [2, { namedComponents: arrow-function, unnamedComponents: arrow-function }],
    react/prop-types: off,
    react/react-in-jsx-scope: off,
    '@typescript-eslint/no-unused-vars': off,
    spaced-comment: [error, always, { markers: ['/'] }],
    unused-imports/no-unused-imports: error,
    unused-imports/no-unused-vars:
      [warn, { vars: all, varsIgnorePattern: ^_, args: after-used, argsIgnorePattern: ^_ }],
    '@typescript-eslint/triple-slash-reference': off,
  }
settings: { react: { version: detect }, import/resolver: { typescript: { project: './' } } }
